
language:
- cpp

before_install:
- pip install —user cpp-coveralls

addons:
sonarcloud:
organization: alexandrtel

script:
- qmake
- make
- ./tests/tests

after_success:
- coveralls —root . -E ".*external.*" -E ".*tests.*"
- build-wrapper-linux-x86-64 —out-dir bw-output make all
- sonar-scanner
-D"sonar.projectKey=AlexandrTel_Lab.1" \
-D"sonar.organization=alexandrtel" \
-D"sonar.sources=." \
-D"sonar.cfamily.build-wrapper-output=bw-output" \
-D"sonar.host.url=https://sonarcloud.io" \
-D"sonar.login=fe90ea8caf22526a9b0622a04d0478830f0854cb"

cache:
directories:
- '$HOME/.sonar/cache'


notifications:
email: false
