language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud:
    organization: "alexandrtel"
    token:
      secure: $SONAR_TOKEN

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  - sonar-scanner
  sonar.projectKey=AlexandrTel_Lab.1
  sonar.projectName=Lab.1
  sonar.projectVersion=1.0
  sonar.sources=.

cache:
  directories:
  - '$HOME/.sonar/cache'

 
notifications:
  email: false
